"""empty message

Revision ID: 6e2442ab9506
Revises: 
Create Date: 2019-07-16 09:27:46.521567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2442ab9506'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('address_2', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=255), nullable=True),
    sa.Column('address_state', sa.String(length=50), nullable=True),
    sa.Column('profile_bio', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('framelib',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('langs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=True),
    sa.Column('rep_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('address_2', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=255), nullable=True),
    sa.Column('address_state', sa.String(length=50), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('abbrev', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dev_frame_lib',
    sa.Column('dev_id', sa.Integer(), nullable=False),
    sa.Column('framelib_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], ),
    sa.ForeignKeyConstraint(['framelib_id'], ['framelib.id'], ),
    sa.PrimaryKeyConstraint('dev_id', 'framelib_id')
    )
    op.create_table('dev_langs',
    sa.Column('dev_id', sa.Integer(), nullable=False),
    sa.Column('lang_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], ),
    sa.ForeignKeyConstraint(['lang_id'], ['langs.id'], ),
    sa.PrimaryKeyConstraint('dev_id', 'lang_id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['org'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_frame_lib',
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('framelib_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['framelib_id'], ['framelib.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('pos_id', 'framelib_id')
    )
    op.create_table('position_langs',
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('lang_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lang_id'], ['langs.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('pos_id', 'lang_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_langs')
    op.drop_table('position_frame_lib')
    op.drop_table('positions')
    op.drop_table('dev_langs')
    op.drop_table('dev_frame_lib')
    op.drop_table('states')
    op.drop_table('orgs')
    op.drop_table('langs')
    op.drop_table('framelib')
    op.drop_table('devs')
    # ### end Alembic commands ###
